### ISSUE TITLE
Features Tracker

### ISSUE THREAD

**Issue by qb20nh** [Apptive-Genie/linkit-app#50]
## Shipped

- [x] Google Login
- [x] Categorizing by folders
- [x] Tagging
- [x] Searching by tag name or url string
- [x] Making notes on links

## Planned

- [ ] Folder sharing
- [ ] Link and folder co-editing
- [ ] Highlighting on link content
- [ ] Friends list
- [ ] Push Notification

## Under Consideration

- [ ] Auto publish by request count / datetime
- [ ] Auto expire by view count / datetime
- [ ] Password protection & additional encryption
